version: '3.8'
services:
    mariadb-phpmyadmin:
      image: mariadb:latest
      stop_grace_period: 45s
      volumes:
        - mariadb-vol-1:/var/lib/mysql/
        - mariadb-socket-vol-1:/var/run/mysqld/
        - ./data/conf/mariadb/:/etc/mariadb/conf.d/:ro,Z
      environment:
        - TZ=${TZ:-UTC}
        - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      restart: always
      ports:
        - "${SQL_PORT:-127.0.0.1:13306}:3306"
      networks:
        phpmyadmin-network:
          aliases:
            - mariadb

    php-fpm-phpmyadmin:
      image: sagesphinx63920/phpmydocker-fpm:latest
      command: "php-fpm -d date.timezone=${TZ}"
      volumes:
        - ./data/web:/web:z
        - mariadb-socket-vol-1:/var/run/mysqld/
        - ./data/conf/fpm/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini:Z
        - ./data/conf/nginx/:/etc/nginx/conf.d/:z
        - ./data/conf/fpm/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf:Z
      environment:
        - TZ=${TZ}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      restart: always
      networks:
        phpmyadmin-network:
          aliases:
            - phpfpm

    nginx-phpmyadmin:
      depends_on:
        - php-fpm-phpmyadmin
        - mariadb-phpmyadmin
      image: nginx:latest
      command: "nginx -g 'daemon off;'"
      environment:
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - HTTP_PORT=${HTTP_PORT:-80}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - TZ=${TZ:-UTC}
      volumes:
        - ./data/web:/web:ro,z
        - ./data/conf/nginx/phpmyadmin:/etc/nginx/sites-enabled/default:z
        - ./data/ssl:/etc/phpmydocker/:ro,z
      ports:
        - "${WEB_BIND:-}:${HTTPS_PORT:-443}:443"
        - "${WEB_BIND:-}:${HTTP_PORT:-80}:80"
      #restart: always
      networks:
        phpmyadmin-network:
          aliases:
            - nginx

networks:
  phpmyadmin-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-phpmyadmin
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  mariadb-vol-1:
  mariadb-socket-vol-1: